package com.pms.domain;

import jakarta.persistence.*;
import lombok.*;

/**
 * Category entity representing a product category with optional parent relationship.
 *
 * Business Logic:
 * - name: Category name (required, max 100 chars)
 * - platform: Platform identifier (required, max 50 chars)
 * - platformCategoryId: External platform category ID (required, max 50 chars)
 * - parent: Parent category (optional, for hierarchical organization)
 * - Timestamps: createdDate (immutable), modifiedDate (auto-updated)
 *
 * Self-reference prevention:
 * - A category cannot be its own parent (checked in service layer)
 *
 * @see com.pms.service.CategoryService for business operations
 * @see com.pms.dto.request.CreateCategoryRequest for input validation
 * @see com.pms.dto.response.CategoryResponse for API output
 */
@Entity
@Table(name = "category")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Category extends BaseEntity {

    /**
     * Unique identifier (auto-generated by database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Category name/label.
     * Max 100 characters, required field.
     * Examples: "Electronics", "Clothing", "Books"
     */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Platform identifier (e.g., marketplace, vendor name).
     * Max 50 characters, required field.
     * Examples: "AMAZON", "SHOPEE", "LAZADA"
     */
    @Column(nullable = false, length = 50)
    private String platform;

    /**
     * External platform's category ID.
     * Used to map to platform-specific category IDs.
     * Max 50 characters, required field.
     * Examples: "cat-12345", "cate_789"
     */
    @Column(nullable = false, length = 50, name = "platform_category_id")
    private String platformCategoryId;

    /**
     * Parent category for hierarchical organization.
     * Nullable: top-level categories have parent = null.
     * Lazy-loaded to avoid N+1 queries.
     *
     * Self-reference prevention rule:
     * A category's parent ID cannot equal its own ID.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id", nullable = true)
    private Category parent;
}
