package com.pms.domain;

import jakarta.persistence.*;
import lombok.*;

/**
 * Category entity — promoted to a standard (oclyx-independent) category (FEATURE_2608_06 / 44).
 *
 * Business Logic:
 * - name: Category name (required, max 100 chars) — the standard tree label
 * - parent: Parent category (optional, for hierarchical organization) — the standard tree
 * - Timestamps: createdDate (immutable), modifiedDate (auto-updated)
 *
 * <p>⚠️ {@code platform} / {@code platformCategoryId} are <b>deprecated</b> (44): columns + getters are kept
 * for backward compatibility with the live {@code CommissionRate} / {@code CategoryController}, but new logic
 * never reads them. They are relaxed to nullable — a new standard category has no platform/code; the
 * per-platform code lives in {@link CategoryMapping} (standard × platform → code). changeset 029 drops their
 * NOT NULL.</p>
 *
 * Self-reference prevention:
 * - A category cannot be its own parent (checked in service layer)
 *
 * @see com.pms.service.CategoryService for business operations
 * @see com.pms.dto.request.CreateCategoryRequest for input validation
 * @see com.pms.dto.response.CategoryResponse for API output
 */
@Entity
@Table(name = "category")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Category extends BaseEntity {

    /**
     * Unique identifier (auto-generated by database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Category name/label.
     * Max 100 characters, required field.
     * Examples: "Electronics", "Clothing", "Books"
     */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * @deprecated (44) Platform identifier. Nullable now — a standard category has no platform; the code
     *             lives in {@link CategoryMapping}. Kept only for live CommissionRate/CategoryController.
     */
    @Deprecated
    @Column(nullable = true, length = 50)
    private String platform;

    /**
     * @deprecated (44) External platform's category ID. Nullable now — owned by {@link CategoryMapping}.
     *             Kept only for backward compatibility.
     */
    @Deprecated
    @Column(nullable = true, length = 50, name = "platform_category_id")
    private String platformCategoryId;

    /**
     * Parent category for hierarchical organization.
     * Nullable: top-level categories have parent = null.
     * Lazy-loaded to avoid N+1 queries.
     *
     * Self-reference prevention rule:
     * A category's parent ID cannot equal its own ID.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id", nullable = true)
    private Category parent;
}
