package com.pms.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.TenantId;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Package entity representing a shipping/packaging option.
 *
 * Business Logic:
 * - type: Package category (e.g., "STANDARD", "EXPRESS", "FRAGILE")
 * - cost: Shipping cost in BigDecimal (2 decimal places)
 * - effectiveDate: Date from which package is valid
 * - isDefault: Only ONE package can have isDefault=true globally.
 *   When creating/updating with isDefault=true, existing default is set to false.
 * - widthCm/lengthCm/heightCm: box dimensions in cm, 0 = unset
 * - boxKind: PURCHASED | RECYCLED. RECYCLED boxes never reach the selling-price calculation (2609_40 D21)
 * - imageUrl: optional box photo; NULL means "draw a shape from the dimensions" (2609_40 D26)
 *
 * @see com.pms.service.PackageService for business operations
 * @see com.pms.dto.request.PackageRequest for input validation
 * @see com.pms.dto.response.PackageResponse for API output
 */
@Entity
@Table(name = "package")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Package {

    /**
     * Unique identifier (auto-generated by database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Tenant dimension (changeset 002). Hibernate auto-sets this on INSERT and auto-filters
    // SELECTs from TenantIdentifierResolver — do NOT add manual tenant conditions to queries.
    @TenantId
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /**
     * Package type/category.
     * Max 50 characters, required field.
     * Examples: "STANDARD", "EXPRESS", "FRAGILE", "OVERSIZED"
     */
    @Column(length = 50, nullable = false)
    private String type;

    /**
     * Shipping cost in monetary units.
     * Decimal format with 2 decimal places (precision: 10,2).
     * Must be >= 0.00.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal cost;

    /**
     * Effective date for this package type.
     * Allows versioning/historical tracking of package rates.
     * Format: ISO date (YYYY-MM-DD)
     */
    @Column(name = "effective_date", nullable = false)
    private LocalDate effectiveDate;

    /**
     * Flag indicating if this is the default package type.
     * BUSINESS RULE: Only one Package globally can have isDefault=true.
     * When set to true, existing default is automatically updated to false.
     */
    @Column(name = "is_default", nullable = false)
    private Boolean isDefault;

    /**
     * Box width in centimetres (PLAN 2609_38 D1 · D2).
     * 0 means UNSET: rows created before this feature were backfilled with 0 (D4), and the
     * request DTO rejects 0 so the value is filled in the next time the box is edited (D5).
     * ⚠️ Display only — never feed this into pricing or channel payloads (D9).
     */
    @Builder.Default
    @Column(name = "width_cm", nullable = false, precision = 5, scale = 1)
    private BigDecimal widthCm = BigDecimal.ZERO;

    /** Box length in centimetres, 0 = unset (PLAN 2609_38 D1 · D4). */
    @Builder.Default
    @Column(name = "length_cm", nullable = false, precision = 5, scale = 1)
    private BigDecimal lengthCm = BigDecimal.ZERO;

    /** Box height in centimetres, 0 = unset (PLAN 2609_38 D1 · D4). */
    @Builder.Default
    @Column(name = "height_cm", nullable = false, precision = 5, scale = 1)
    private BigDecimal heightCm = BigDecimal.ZERO;

    /**
     * How we got this box (PLAN 2609_40 D20 · D21). Rows created before the feature were backfilled to
     * {@link BoxKind#PURCHASED} — every box that existed then was bought.
     *
     * <p>🔴 {@link BoxKind#RECYCLED} boxes are invisible to the selling-price calculation: the list API
     * filters them out for pricing dropdowns and
     * {@link com.pms.service.MasterChannelConfigService#resolvePackage} rejects them outright. A recycled
     * box costs 0, so one slipping into pricing would silently price goods off a zero-cost box.</p>
     *
     * <p>⚠️ Only one validation branches on this value: a recycled box may cost 0, a purchased box may not
     * (see {@code PackageServiceImpl}). A recycled box can never be the default box.</p>
     */
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(name = "box_kind", nullable = false, length = 20)
    private BoxKind boxKind = BoxKind.PURCHASED;

    /**
     * Photo of the box — the value returned by {@code ImageStorageService} (disk-relative path on
     * local/test, public S3 URL on dev/prod), uploaded through {@code POST /api/admin/package/{id}/image}.
     *
     * <p>NULL is a normal state (PLAN 2609_40 D26): screens draw a shape scaled to the box dimensions
     * instead, so nothing waits for a photo. ⚠️ Clearing a photo only nulls this column — the stored object
     * is deliberately NOT deleted, because the same value may be referenced elsewhere.</p>
     *
     * <p>⚠️ The edit endpoint ({@code PATCH}) never touches this column; the upload endpoint owns it.</p>
     */
    @Column(name = "image_url", length = 500)
    private String imageUrl;
}
