package com.pms.domain;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Package entity representing a shipping/packaging option.
 *
 * Business Logic:
 * - type: Package category (e.g., "STANDARD", "EXPRESS", "FRAGILE")
 * - cost: Shipping cost in BigDecimal (2 decimal places)
 * - effectiveDate: Date from which package is valid
 * - isDefault: Only ONE package can have isDefault=true globally.
 *   When creating/updating with isDefault=true, existing default is set to false.
 *
 * @see com.pms.service.PackageService for business operations
 * @see com.pms.dto.request.PackageRequest for input validation
 * @see com.pms.dto.response.PackageResponse for API output
 */
@Entity
@Table(name = "package")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Package {

    /**
     * Unique identifier (auto-generated by database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Package type/category.
     * Max 50 characters, required field.
     * Examples: "STANDARD", "EXPRESS", "FRAGILE", "OVERSIZED"
     */
    @Column(length = 50, nullable = false)
    private String type;

    /**
     * Shipping cost in monetary units.
     * Decimal format with 2 decimal places (precision: 10,2).
     * Must be >= 0.00.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal cost;

    /**
     * Effective date for this package type.
     * Allows versioning/historical tracking of package rates.
     * Format: ISO date (YYYY-MM-DD)
     */
    @Column(name = "effective_date", nullable = false)
    private LocalDate effectiveDate;

    /**
     * Flag indicating if this is the default package type.
     * BUSINESS RULE: Only one Package globally can have isDefault=true.
     * When set to true, existing default is automatically updated to false.
     */
    @Column(name = "is_default", nullable = false)
    private Boolean isDefault;
}
